/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Time = IDL.Int;
export const ToolEvent = IDL.Record({
  'timestamp' : Time,
  'toolName' : IDL.Text,
});
export const PlatformStats = IDL.Record({
  'totalFiles' : IDL.Nat,
  'recentActivity' : IDL.Vec(ToolEvent),
  'totalSessions' : IDL.Nat,
  'toolUsage' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
  'getRecentActivity' : IDL.Func([], [IDL.Vec(ToolEvent)], ['query']),
  'getToolCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getToolStats' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getTotalFiles' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalSessions' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordFile' : IDL.Func([], [IDL.Nat], []),
  'recordSession' : IDL.Func([], [IDL.Nat], []),
  'recordToolUsage' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toolExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'updateAdminPassword' : IDL.Func([IDL.Text], [], []),
  'verifyAdminPassword' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Time = IDL.Int;
  const ToolEvent = IDL.Record({ 'timestamp' : Time, 'toolName' : IDL.Text });
  const PlatformStats = IDL.Record({
    'totalFiles' : IDL.Nat,
    'recentActivity' : IDL.Vec(ToolEvent),
    'totalSessions' : IDL.Nat,
    'toolUsage' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
    'getRecentActivity' : IDL.Func([], [IDL.Vec(ToolEvent)], ['query']),
    'getToolCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getToolStats' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getTotalFiles' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalSessions' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordFile' : IDL.Func([], [IDL.Nat], []),
    'recordSession' : IDL.Func([], [IDL.Nat], []),
    'recordToolUsage' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toolExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'updateAdminPassword' : IDL.Func([IDL.Text], [], []),
    'verifyAdminPassword' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };