/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ExtendedStats {
  'totalFiles' : bigint,
  'imageFiles' : bigint,
  'hourlyFileCount' : bigint,
  'magicButtonClicks' : bigint,
  'pdfFiles' : bigint,
  'totalSessions' : bigint,
  'sharePopupTriggers' : bigint,
  'toolUsage' : Array<[string, bigint]>,
}
export interface PlatformStats {
  'totalFiles' : bigint,
  'recentActivity' : Array<ToolEvent>,
  'totalSessions' : bigint,
  'toolUsage' : Array<[string, bigint]>,
}
export type Time = bigint;
export interface ToolEvent { 'timestamp' : Time, 'toolName' : string }
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllToolStates' : ActorMethod<[], Array<[string, boolean]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExtendedStats' : ActorMethod<[], ExtendedStats>,
  'getHourlyFileCount' : ActorMethod<[], bigint>,
  'getPlatformStats' : ActorMethod<[], PlatformStats>,
  'getRecentActivity' : ActorMethod<[], Array<ToolEvent>>,
  'getReferralCount' : ActorMethod<[string], bigint>,
  'getToolCount' : ActorMethod<[string], bigint>,
  'getToolEnabled' : ActorMethod<[string], boolean>,
  'getToolStats' : ActorMethod<[], Array<[string, bigint]>>,
  'getTotalFiles' : ActorMethod<[], bigint>,
  'getTotalSessions' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordFile' : ActorMethod<[], bigint>,
  'recordFileTyped' : ActorMethod<[string], bigint>,
  'recordMagicButtonClick' : ActorMethod<[], bigint>,
  'recordReferral' : ActorMethod<[string], bigint>,
  'recordSession' : ActorMethod<[], bigint>,
  'recordSharePopup' : ActorMethod<[], bigint>,
  'recordToolUsage' : ActorMethod<[string], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setToolEnabled' : ActorMethod<[string, boolean], undefined>,
  'toolExists' : ActorMethod<[string], boolean>,
  'updateAdminPassword' : ActorMethod<[string, string], boolean>,
  'verifyAdminPassword' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];